### ISSUE TITLE
산학프로젝트 주제 정하기

### ISSUE THREAD

**Issue by chaebumguen** [chaebumguen/ChaeHongJung#1]
'추천 시스템'이라는 범주 내에서 주제를 정해봅시다.

저는 사용자의 위치의 날씨에 따라서 노래를 추천해주는 시스템을 생각해보았습니다.

조원분들의 의견도 댓글로 달아주시기를 부탁해요!

**Comment by honggilgim** [comment]
그날의 날씨, 기분, 보고싶은 장르 등을 입력 데이터로 받아서 영화를 추천해주는 시스템을 생각해 보았습니다.

**Comment by cksgml414** [comment]
저는 사용자가 칼로리, 영양소 비율을 설정하면 음식을 추천해주는 프로그램을 생각해 보았습니다.

**Comment by bytecell** [comment]
우측 상단에 assignees 를 통해,
이 이슈에 대하여 논의에 참여해야 할 대상을 지정할 수 있습니다.

"주제 정하기"는 팀원 모두가 참여할 수 있는 이슈이므로,
팀원 모두를 assign 해보기 바랍니다.

**Comment by chaebumguen** [comment]
이슈 닫겠습니다!
