### ISSUE TITLE
데이터 유지를 위한 기능 생성시 세션, 쿠키 선택 이슈

### ISSUE THREAD

**Issue by honggilgim** [chaebumguen/ChaeHongJung#10]
데이터 유지를 위해서, 쿠키 혹은 세션 둘 중 하나를 사용하려고 합니다.

세션이 쿠키에 비해 보안적 안전성이 더 높으나, 세션은 쿠키에 비해서 서버 자원을 많이 소모합니다. 저희는 그래서 쿠키를 통해서 데이터 유지 기능을 실현하려 합니다.

의견이 있으면 달아주시기 바랍니다.

**Comment by chaebumguen** [comment]
네 좋아요

**Comment by honggilgim** [comment]
일단 쿠키 쪽으로 진행했습니다.
