### ISSUE TITLE
INPUT(입력 값)에 영양소 비율을 항목 제거에 관한 이슈입니다.

### ISSUE THREAD

**Issue by cksgml414** [chaebumguen/ChaeHongJung#2]
이러한 이슈가 나온 이유는 여러가지가 있지만 금일 필자가 초임 선생님들을 대상으로 하여 영양 교육을 진행하였습니다.
아래 블로그 글을 참고해주세요. 
https://blog.naver.com/NBlogTop.naver?isHttpsRedirect=true&blogId=cksgml414&Redirect=Dlog&Qs=/cksgml414/222518696772&createTime=1632748317000
첫번째. 혼합식을 먹는 현대 사회에서 영양소 비율은 굳이 의미가 없음
두번째. 품종 개량 등의 이유로 데이터 값의 신뢰성이 떨어짐

**Comment by chaebumguen** [comment]
전문적인 시선에서의 의견인 것 같네요. 무슨 의도인지 인지했습니다.
또한 원할한 데이터 분석을 위해서도 좋은 의견인 것 같습니다.
강력하게 고려해보는 것이 좋다고 생각합니다!

**Comment by honggilgim** [comment]
블로그 검토해봤는데, 블로그에 나온 내용대로라면 영양소 비율을 빼고 맛쪽으로 설정하는 것도 괜찮은 기능을 만들어 낼 수 있을 것 같습니다. 저도 빼는것 쪽으로 진행하는 것이 좋다고 생각합니다.

**Comment by chaebumguen** [comment]
다만 영양소 비율이 빠져버리게 되면 음식을 추천하는 과정에서 (많은 이용자들이 아직 사용하지 않아 추천 알고리즘이 초기일 경우)칼로리에 맞는 음식들이 모조리 나와버리면 의미가 없어질 것 같다고 생각했는데, 이 부분은 위의 의견과 같이 맛을 설정하는 것이 좋을 것 같아보이는데 어떨까요?

**Comment by honggilgim** [comment]
영양소 비율이 줄어든만큼, 맛이나 취향쪽으로 데이터를 잘 가공하여 사용하면 더욱 좋은 프로그램으로 만들 수 있을 것 같습니다. 처음에 input 값으로 사용자의 간단한 성향을 조사하여 받고, 이후 추천해준 값으로 더욱 좋은 음식을 추천해준다면 좋은 서비스로 만들어낼 수 있을 것 같습니다.

**Comment by cksgml414** [comment]
동감합니다. 영양소 비율이 생각보다 애매모호한 부분이 많아서 빼는것이 좋을것 같고 홍길 팀원 의견에 동감합니다.
