### ISSUE TITLE
성능 평가 방법에 관한 이슈입니다.

### ISSUE THREAD

**Issue by honggilgim** [chaebumguen/ChaeHongJung#3]
성능평가 방식으로 데이터를 산정해서 평가하는 방법도 있으나, 현재 저희 구현의 상태로는 성능평가에 정확한 데이터를 얻을 수 없을 것이라 생각합니다. 그리고 저희 앱의 특성 상, 기존의 앱과 비교가 어려운 부분이 있습니다. 그래서 저는 지금은 성능평가를 설문조사를 통한 기존의 앱과의 선호도를 묻는 방향으로 진행했으면 좋겠습니다.

그리고 후에, 구현이 어느정도 완료되면 그때 다시, 데이터를 입력하여 회원의 선호 음식이 잘 나오는지를 묻는 방향으로 성능평가를진행해보아도 괜찮을 것 같습니다.

의견을 제시해 주십시오.

**Comment by cksgml414** [comment]
저도 설문조사를 통하여 선호도 조사를 하는것이 좋을것 같습니다.
마침 직장 선생님들과 제 클라이언트들에게 따로 설문을 부탁하면 더 양질의 설문조사가 될 것 같습니다.

* 제가 설문조사에 부가설명을 첨언하여 설문자들이 이해하기 쉽도록 정리하여 제작하였습니다.
