### ISSUE TITLE
영양DB 가공 관련이슈입니다. (about 칼로리 데이터)

### ISSUE THREAD

**Issue by cksgml414** [chaebumguen/ChaeHongJung#5]
식품영양DB 가공 시 어떻게 해야 작업을 수월하게 할 수 있을지에 대한 이슈입니다.

아시다 싶이 영양 DB는 영양소와 칼로리를 1회 제공량(1회분)을 기준으로 제공하고 있습니다.

우선 제가 생각하는 방법은

1회 제공량당 칼로리가 70이상인 식품들을 먼저 분류합니다. *이유는 생선, 닭가슴살 등이 우리가 섭취하는 주요 섭취 급원 중 
거의 가장 낮은 칼로리를 갖고 있긴 때문입니다.
이후 칼로리를 구간별로 나누는게 좋다고 생각합니다. 70~200, 200~300, 300~400 이렇게 100kcal 단위로 나누고 탄수화물 충족
되는 음식인지 아닌지만 구별하면 대략적인 1차 가공은 끝이라고 보시면 될 것 같습니다. 다른 분들 의견도 남겨주세요

**Comment by honggilgim** [comment]
100kcal 단위로 나누는 것은 매우 괜찮은 생각인 것 같습니다. 그런데, 저희의 인풋에 음식의 종류도 있는만큼 음식의 종류를 넣어서 분류하는 것도 1차 가공쪽으로 넣으면 더욱 좋을 것 같습니다. 다른 조건들도 물론 중요하지만 저는 1차 가공에서는 음식의 종류를 분류하는 일이 더욱 중요하다고 생각합니다.

**Comment by chaebumguen** [comment]
칼로리 70 이상인 식품들을 분류하는 이유가 잘 이해가 되질 않는데 생선, 닭가슴살로 70kcal를 섭취할 시 최소 영양소가 충족된다는 의미인가요? 또 탄수화물 충족되는 음식인지 아닌지 구별하는 이유도 몰라서 구체적인 설명 부탁드립니다.
