### ISSUE TITLE
지난번 발표 이후 기능 추가 여부에 대한 이슈입니다.

### ISSUE THREAD

**Issue by cksgml414** [chaebumguen/ChaeHongJung#7]
지난번 중간 발표에서 이동철 학생이 주었던 질문입니다.

아무래도 타 서비스에 비해 기능이 다소 아쉽다는 의견이었는데 곰곰히 생각해보니 맞는 말 같습니다.

헬스케어 플랫폼으로서 더욱 더 성장하려면 단순한 계산기처럼 칼로리를 입력하고 음식을 출력받는것 이외에도 다른 기능들이 더 있으면

좋겠다는 생각을 하였습니다.

우선 제가 생각해둔 아이디어가 몇 가지 있습니다.

1. 다이어트, 운동에 관한 칼럼 게시판  (이 부분은 제가 블로그에 직접 게시하고 있기도 하고 제가 근무하는 센터 선생님들이 주기적으로 업로드하고 있는 다양한 정보를 가져올 수 있습니다.)

2. 피트니스 센터 or 운동 코치들 입점 : 결국 인간의 욕심을 끝이 없기 때문에 영양소DB 가공을 통한 정보 제공만으로는 부족할 수 있다고 
생각이 들었습니다. 전문가들을 입점시켜 온라인 코칭 및 컨설팅을 생각하고 있습니다.

1번의 부분은 구현에서 어려움을 겪진 않을 것 같고 2번의 경우 실시간 채팅을 구현하는 방법을 구상해보아야 할 것 같습니다.

자유로운 의견 부탁드립니다.

**Comment by honggilgim** [comment]
칼럼 게시판 정도는 구현한 기능을 전부 구현한 뒤에, 시간이 남으면 시도해볼 수도 있지만 2번 방안에 대해서는 너무 어려운 일이라고 생각됩니다. 1번 방향으로는, 구현 후 시간이 남을 경우 긍정적으로 생각해 볼 수 있지만, 2번 방안은 시간을 생각해 볼 때 힘들 것 같습니다.

**Comment by chaebumguen** [comment]
아이디어 자체는 기능적인 업그레이드에 충분히 도움이 되는 컨텐츠로 발전시킬 수 있을 것 같고 고려해볼만 하다고 봅니다. 다만 저희 개발 속도를 볼 때 조금은 힘들지 않을까 생각합니다. 향후 진척율을 보고 다시 논의해보도록 해요.
