### ISSUE TITLE
회원가입 페이지 받아야 할 정보 관련 이슈입니다.

### ISSUE THREAD

**Issue by honggilgim** [chaebumguen/ChaeHongJung#8]
로그인 기능과 회원가입 기능을 구현하기 위해서, 회원가입 관련 기능을 만들던 도중에, 회원가입과 관련하여 무슨 정보를 받아야 할지에 대해 팀원들의 생각을 들어볼 필요가 있다고 생각해서 이슈를 작성하게 되었습니다.

현재 생각한 회원가입 정보는 다음과 같습니다.
아이디
패스워드
나이
체중
신장
성별
활동량 (상, 중, 하)

이 정보는 권장 칼로리 산출에도 들어갈 정보입니다.

**Comment by cksgml414** [comment]
활동량은 빼도 될 듯 합니다.
대신 대한비만협회에서 제안하는 권장 칼로리임을 명시하고 남, 녀로 구분하여 다이어터를 위한 칼로리 데이터를 제공할 생각입니다. 
활동량에 따라 칼로리 섭취량이 달라지는것은 맞으나 각기 다른 신체 환경과 생활 패턴을 갖고 있으므로 신뢰성있는 정보를 주기 어려울것 같습니다. 그래서 활동량을 대신하여 유산소는 최소 주 ~회 이상 타는 사용자에게 적용된다고 간단한 가이드 라인과 함께 제공할 생각입니다. 제 생각이 어떠신지요
